services:
  app:
    image: ghcr.io/aldo-leka/ai-quiz-myself:${IMAGE_TAG:-latest}
    container_name: quizplus-app
    restart: unless-stopped
    env_file:
      - .env.production
    expose:
      - "3000"
    networks:
      - ingress
      - database

networks:
  ingress:
    external: true
    name: yhp99hliq5cujkenfl2ln6rp
  database:
    external: true
    name: quizplus-internal
