export const moneyLadder = [500, 1000, 2000, 3000, 5000, 7000, 10000, 20000, 30000, 50000, 100000, 250000, 500000, 1000000]

export const loadingActions = [
    "Warming up the spotlight",
    "Cueing dramatic music",
    "Adjusting the lifelines",
    "Counting the prize money",
    "Locking in the final answer",
    "Phoning a friend",
    "Asking the audience",
    "Shuffling the questions",
    "Tightening the host’s tie",
    "Building the suspense",
    "Stacking the million",
    "Filling the briefcase",
    "Checking the prize ladder",
    "Securing the jackpot",
    "Polishing the cheque",
    "Printing imaginary money",
    "Dim the lights",
    "Raising the tension",
    "Cue audience gasp",
    "Loading dramatic pause",
    "Lowering the studio hush",
    "Suspense levels rising",
    "Mic check… one, two, millionaire",
    "Rehearsing the host’s lines",
    "Bribing the audience with applause",
    "Loading studio effects",
    "Shuffling the cue cards"
]
